"""Lock the Python protocol port to the SAME reference frames used by the Android app
(EcoUnworthy tools/verify_inverter_codec.py), generated by the real pysolarmanv5 library
(logger serial 1234567890, sequence 0x5A). Plus a decode test for scaling/sign logic.

Run from the project root:  python tests/test_codec.py   (or: pytest)
"""
import math
import os
import sys
import unittest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from solardash import inverter
from solardash.codec import (
    crc16_modbus,
    modbus_parse_holding,
    modbus_read_request,
    v5_decode,
    v5_encode,
)


class CodecReferenceTest(unittest.TestCase):
    """Byte-for-byte equality with pysolarmanv5-generated reference frames."""

    def test_modbus_request(self):
        req = modbus_read_request(1, 0x0100, 1)
        self.assertEqual(req.hex(), "01030100000185f6")

    def test_v5_encode(self):
        req = modbus_read_request(1, 0x0100, 1)
        frame = v5_encode(1234567890, 0x5A, req)
        self.assertEqual(
            frame.hex(),
            "a5170010455a00d202964902000000000000000000000000000001030100000185f6fc15",
        )

    def test_v5_decode_and_parse(self):
        resp = bytes.fromhex(
            "a5150010155a00d202964902010000000000000000000000000103020054b9bb1815"
        )
        mb = v5_decode(resp)
        self.assertIsNotNone(mb)
        self.assertEqual(mb.hex(), "0103020054b9bb")
        self.assertEqual(modbus_parse_holding(mb, 1), [0x0054])

    def test_crc16_modbus_known(self):
        # CRC of the request body (without its own CRC) must equal the appended bytes.
        body = bytes([1, 3, 0x01, 0x00, 0x00, 0x01])
        crc = crc16_modbus(body)
        self.assertEqual(bytes([crc & 0xFF, (crc >> 8) & 0xFF]).hex(), "85f6")

    def test_rejects_bad_crc(self):
        bad = bytes.fromhex("01030200540000")  # last 2 bytes are a wrong CRC
        self.assertIsNone(modbus_parse_holding(bad, 1))

    def test_rejects_wrong_slave(self):
        mb = bytes.fromhex("0103020054b9bb")
        self.assertIsNone(modbus_parse_holding(mb, 0xFF))


class InverterDecodeTest(unittest.TestCase):
    """Scaling, signedness, and derived-field logic in SrneInverter.decode()."""

    def setUp(self):
        self.regs = {
            0x0100: 95,        # SOC 95 %
            0x0101: 532,       # battery 53.2 V
            0x0102: 100,       # raw +100 -> normalised to -10.0 A (discharging)
            0x0103: 0xFFFB,    # -5 raw -> -0.5 degC (signed)
            0x0107: 1500,      # PV1 150.0 V
            0x0108: 85,        # PV1 8.5 A  -> 1275 W
            0x010F: 1490,      # PV2 149.0 V
            0x0110: 50,        # PV2 5.0 A  -> 745 W
            0x0213: 1201,      # grid 120.1 V
            0x0215: 5998,      # 59.98 Hz
            0x021B: 1200,      # load L1 1200 W
            0x0232: 800,       # load L2 800 W
            0x0204: 5,         # one active fault code
            0x0205: 0, 0x0206: 0, 0x0207: 0,
            0x0210: 2,         # machine state
        }
        self.s = inverter.decode(self.regs)

    def test_scaling(self):
        self.assertEqual(self.s.battery_soc, 95)
        self.assertTrue(math.isclose(self.s.battery_voltage, 53.2))
        self.assertTrue(math.isclose(self.s.grid_frequency, 59.98))

    def test_signed_current_normalised(self):
        # raw +100 with -0.1 scale -> -10.0 A (app convention: - = discharge)
        self.assertTrue(math.isclose(self.s.battery_current, -10.0))

    def test_signed_temperature(self):
        self.assertTrue(math.isclose(self.s.battery_temp, -0.5))

    def test_derived_pv_power(self):
        self.assertTrue(math.isclose(self.s.pv1_power, 1275.0))
        self.assertTrue(math.isclose(self.s.pv2_power, 745.0))
        self.assertTrue(math.isclose(self.s.pv_power, 2020.0))

    def test_derived_load_total(self):
        self.assertEqual(self.s.load_total, 2000)

    def test_battery_power(self):
        self.assertTrue(math.isclose(self.s.battery_power, 53.2 * -10.0))

    def test_faults(self):
        self.assertEqual(self.s.fault_codes, [5])
        self.assertTrue(self.s.has_fault)

    def test_has_core_gate(self):
        self.assertTrue(inverter.has_core(self.regs))
        self.assertFalse(inverter.has_core({0x0101: 0}))
        self.assertFalse(inverter.has_core({}))

    def test_merge_carries_forward(self):
        prev = {0x0101: 500, 0x0107: 1000}
        fresh = {0x0101: 532}  # PV1 block dropped this cycle
        merged = inverter.merge(prev, fresh)
        self.assertEqual(merged[0x0101], 532)   # fresh wins
        self.assertEqual(merged[0x0107], 1000)  # carried forward


if __name__ == "__main__":
    unittest.main(verbosity=2)
